package exceptions;

public class ExceptionDemo {
	
	public static int divide(int a, int b) throws DivideByZero {
		if(b==0) {
			throw new DivideByZero();
		}
		
		return a/b;
	}

	public static void main(String[] args) throws DivideByZero {
		// TODO Auto-generated method stub
		try {
			divide(1, 1);
		}catch(DivideByZero d) {
			d.printStackTrace();
		}
		
	}

}
